package com.mccabe.rest;

public class Query {
    private static final String OVERVIEW =  "SELECT SYSTEM_ID, PACKAGE_NAME_KO, COUNT(PACKAGE_NAME_KO) TOTAL_PROGRAM, COUNT(CASE WHEN TESTED != 0 THEN 1 END) PROGRAM_TESTED,\n" +
            "  COUNT(CASE WHEN COVERAGE >= 80 THEN 1 END) OVER_COVERAGE, COUNT(CASE WHEN COVERAGE < 80 THEN 1 END) UNDER_COVERAGE,\n" +
            "  SUM(TOTAL_FUNC_CNT) TOTAL_FUNC_CNTS, SUM(TESTED) FUN_TESTED,\n" +
            "  (SUM(COVERAGE) / COUNT(PACKAGE_NAME_KO)) COVERAGE, (COUNT(PACKAGE_NAME_KO) - SUM(TESTED)) UNTESTED\n" +
            "  FROM (SELECT SYSTEM_ID, PACKAGE_NAME_KO, FILE_NAME, COUNT(FILE_NAME) TOTAL_FUNC_CNT, COUNT(FILE_NAME) - COUNT(DECODE(COV_COVERAGE, 0, 1)) TESTED,\n" +
            "         SUM(COV_COVERAGE) / CASE WHEN (COUNT(FILE_NAME) - COUNT(DECODE(COV_COVERAGE, 0, 1))) <= 0 THEN 1 ELSE (COUNT(FILE_NAME) - COUNT(DECODE(COV_COVERAGE, 0, 1))) END COVERAGE\n" +
            "        FROM (SELECT SYSTEM_ID, PACKAGE_NAME_KO, FILE_PACKAGE, FILE_NAME, FUNTION_NAME, COV_COVERAGE  FROM REPORT_TABLE, PACKAGE_NAME WHERE PACKAGE_NAME.PACKAGE_NAME = REPORT_TABLE.FILE_PACKAGE AND FILE_DATE = '{date}')\n" +
            "        GROUP BY SYSTEM_ID, PACKAGE_NAME_KO, FILE_NAME)\n" +
            "GROUP BY SYSTEM_ID, PACKAGE_NAME_KO, PACKAGE_NAME_KO";
    public static String getOverView(String where) {
        return OVERVIEW.replace("{date}", where);
    }
}
